### ISSUE TITLE
Enhancement: only show items on statusbar if terminal is open or focused

### ISSUE THREAD

**Issue by uwla** [trybick/vscode-terminal-zoom#5]
It makes no sense to have the items on statusbar if there is no terminal open. The items occupy precious space in such cases.

By the way, thanks for the extension.

**Comment by trybick** [comment]
Makes sense!  It looks like we can use the `window.terminals` API to check if any terminals are open 
https://code.visualstudio.com/api/references/vscode-api#window

Then we hide it here
https://github.com/trybick/vscode-terminal-zoom/blob/master/src/extension.ts#L29

Let me know if you're interested in trying it, otherwise I will try to get to it when I can

**Comment by uwla** [comment]
I can try solve it. Next wee I'll have time for that.

I'm also developing VSCOde extensions, so this will be good for me to learn more about the API.

**Comment by trybick** [comment]
@uwla Opened #6 to address this

**Comment by trybick** [comment]
@uwla If you get a chance, is it working now as expected?

**Comment by uwla** [comment]
Hello @trybick.

I updated the extension and it does not display the zoom icons in the status bar if no terminal is opened. However, it does display the icons if a terminal is opened but hidden (such as the terminal panel) and the current window is a normal file. I believe the proper behavior would be to only display the icons if the current editor is the terminal, not a normal file editor.

**Comment by trybick** [comment]
That is a know limitation of the fix I applied (see comment https://github.com/trybick/vscode-terminal-zoom/pull/6/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R32).

However! I'm glad you said that because I found a possible solution using your words asking chat gpt. It looks like this could be the key. Perhaps we could use the `onDidChangeActiveTextEditor` event.

**Chat gpt answer:**
Yes, in the VSCode Extension API, you can determine the type of the current editor using the `TextDocument` object. The `TextDocument` object represents the text content of the currently opened file in the editor.

You can check if the current editor is displaying a text file or a terminal by examining the `TextDocument`'s `uri` property. The `uri` property contains information about the file being edited, including its scheme. For regular text files, the scheme would typically be `"file"`, while for terminals, it would be something like `"output"`.

Here's how you can do it:

```typescript
import * as vscode from 'vscode';

// Get the currently active text editor
const activeEditor = vscode.window.activeTextEditor;

if (activeEditor) {
    // Get the document associated with the active editor
    const document = activeEditor.document;

    // Check the scheme of the document's URI
    if (document.uri.scheme === 'file') {
        console.log('Current editor is a text file.');
    } else if (document.uri.scheme === 'output') {
        console.log('Current editor is a terminal.');
    } else {
        console.log('Current editor is of unknown type.');
    }
} else {
    console.log('No active text editor.');
}
```

This code snippet checks if there's an active text editor and then examines the scheme of its associated document's URI to determine whether it's a regular text file or a terminal.

**Comment by trybick** [comment]
Played around with `onDidChangeActiveTextEditor` and `onDidChangeActiveTerminal`. Unfortunately they don't fire at the right times for this use case. For example, if you're in a text document and click to the terminal, the terminal event won't fire unless it's a brand new terminal being opened. Likewise, when clicking from the terminal to a text document, if it was the previously open text document, it won't fire the event.

At this point it looks like there's nothing in the API that can help solve this so will close. I feel the recent change is at least a slight improvement.

**Comment by uwla** [comment]
I see. That's bad. Let's wait for a new API then, that can help detect it.

**Comment by trybick** [comment]
Thanks for bringing the original suggestion here @uwla , appreciate it!

**Comment by uwla** [comment]
@trybick, what about adding a command that will add/remove the TerminalZoom icon in the statusbar? Currently, we can show or hide it by manually clicking on the statusbar and toggling its visibility. But, using the mouse is slow. If you can add an extension keyboard shortcut that will toggle the existence of TerminalZoom in statusbar, that would be helpful!

I am not sure if it the VSCode user can achieve such behavior just by tweaking settings. That's because the presence of statusbar commands is defined by the extension. While the user can manually hide or show them using the mouse, I am not aware if there if it can be done via keyboard settings for any extension statusbar command. That's why I believe it may only be possible if the extension developer adds such feature.
